### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by xiaolan92** [LiJinShi/vue_keepAlive#1]
很感谢你的文章帮了我的忙,但是我又发现一个问题。
```
activated(){
            setTimeout(()=>{
                this.$parent.$refs.view.scrollTop=this.$store.state.RecommendScrollTop;

            },50);


        },

```

这样写才能生效,但是这个时间不好把握,那个博主能帮我解释一下吗？

*****
好吧，我比较追求完美,但是这样写总觉得不太好，this.$nextTick也试了，不行

**Comment by LiJinShi** [comment]
这样写确实不太好，整体的解决方案还是有一定瑕疵。。但我和同事也在总结出另一套关于缓存vue页面的方案，但目前不太好开源

**Comment by LiJinShi** [comment]
这样写确实不太好，整体的解决方案还是有一定瑕疵。。但我和同事正总结出另一套关于缓存vue页面的方案，但目前不太好开源

**Comment by xiaolan92** [comment]
@LiJinShi 多谢了，其实我在想，这应该是vue异步更新DOM时间不一的问题，什么时候找一篇文章看看，毕竟我是个菜鸟。
